/// Multilingual dictionary supporting Assamese, Bengali, Hindi, and English for Dementia Seniors
class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      'appTitle': 'Smriti Sahayak',
      'brandSubtitle': 'AI Cognitive & Memory Companion',
      'greeting': 'Namaskar, Biren Babu!',
      'date': 'Monday, 31 August 2026',
      'listenGreeting': 'Listen to Daily Greeting',
      'calmTitle': 'Calm Me Down & Reminiscence',
      'calmDesc': 'Relax your mind with familiar sights and guided breathing.',
      'sosTitle': 'Emergency Wander Assistance',
      'sosDesc': '1-touch call to daughter Priya & clinician beacon.',
      'exercises': 'Daily Cognitive Exercises',
      'ddaActive': 'Adaptive AI Engine Active (Level 2)',
      'game1Title': 'Family Recall Game',
      'game1Sub': 'Recognize daughter Priya and family members with voice anchors.',
      'game2Title': 'Daily Routine Sequencing',
      'game2Sub': 'Arrange tea, medicine, garden walk in chronological order.',
      'game3Title': 'Cultural Memory Match',
      'game3Sub': 'Pair regional symbols: Japi, Gamosa, Brass Bell, Flute.',
      'game4Title': 'Sound & Echo Memory',
      'game4Sub': 'Listen to soothing temple bells and stream soundscapes.',
      'playGame': 'Play Exercise',
      'confirmTaken': 'Confirm Taken',
      'listenInstructions': 'Listen Instructions',
      'schedule': "Biren Babu's Daily Schedule",
      'completed': 'Completed',
      'pending': 'Pending',
      'breatheIn': 'Breathe In Slowly (4s)',
      'breatheHold': 'Hold Gently (7s)',
      'breatheOut': 'Exhale Softly (8s)',
      'listenPriyaVoice': "Play Priya's Comfort Message",
    },
    'as': {
      'appTitle': 'স্মৃতি সহায়ক',
      'brandSubtitle': 'কৃত্ৰিম বুদ্ধিমত্তা চালিত স্মৃতি সহযোগী',
      'greeting': 'নমস্কাৰ, বীৰেন বাবু!',
      'date': 'সোমবাৰ, ৩১ আগষ্ট ২০২৬',
      'listenGreeting': 'দৈনিক শুভবাৰ্তা শুনক',
      'calmTitle': 'মন শান্ত কৰক আৰু পুৰণি স্মৃতি',
      'calmDesc': 'চাহ বাগিচাৰ শান্ত পৰিৱেশ আৰু প্ৰাণায়ামেৰে মন সুস্থিৰ কৰক।',
      'sosTitle': 'জৰুৰীকালীন সাহাৰ্য্য আৰু সন্ধান',
      'sosDesc': 'কন্যা প্ৰিয়ালৈ ১-স্পৰ্শত জৰুৰীকালীন সংকেত পঠিয়াওক।',
      'exercises': 'দৈনিক মগজুৰ স্মৃতি অনুশীলন',
      'ddaActive': 'স্বয়ংক্রিয় এআই অভিযোজন সক্ৰিয় (স্তৰ ২)',
      'game1Title': 'পৰিয়ালৰ চিনাকি খেল ("মুখাবয়ব")',
      'game1Sub': 'মৰমৰ জীয়াৰী প্ৰিয়া আৰু আত্মীয়ৰ মাত শুনি চিনি লওক।',
      'game2Title': 'দৈনিক কৰ্তব্যৰ ক্ৰম ("দৈনিক ক্ৰম")',
      'game2Sub': 'চাহ খোৱা, দৰব খোৱা আৰু ফুৰাৰ সঠিক সময় সজাওক।',
      'game3Title': 'সংস্কৃতিৰ স্মৃতি মিলন ("সংস্কৃতি মেল")',
      'game3Sub': 'জাপী, গামোচা, কাঁহৰ ঘণ্টা আৰু বাঁহীৰ সঠিক জোৰ মিলাওক।',
      'game4Title': 'ধ্বনি আৰু প্ৰতিধ্বনি স্মৃতি ("ধ্বনি স্মৃতি")',
      'game4Sub': 'মন্দিৰৰ ঘণ্টা, কুলিৰ মাত আৰু জুৰিৰ শব্দ চিনি পাওক।',
      'playGame': 'খেল আৰম্ভ কৰক',
      'confirmTaken': 'দৰব খোৱা হ’ল',
      'listenInstructions': 'দৰবৰ নিয়ম শুনক',
      'schedule': 'বীৰেন বাবুৰ দৈনিক সময়সূচী',
      'completed': 'সম্পূৰ্ণ হ’ল',
      'pending': 'বাকী আছে',
      'breatheIn': 'দীঘলকৈ উশাহ লওক (৪ ছেকেণ্ড)',
      'breatheHold': 'ধৰি ৰাখক (৭ ছেকেণ্ড)',
      'breatheOut': 'লাহেকৈ এৰি দিয়ক (৮ ছেকেণ্ড)',
      'listenPriyaVoice': 'প্ৰিয়াৰ শান্তিপূৰ্ণ বাৰ্তা শুনক',
    },
    'bn': {
      'appTitle': 'স্মৃতি সহায়ক',
      'brandSubtitle': 'এআই চালিত মানসিক ও স্মৃতি সহযোগী',
      'greeting': 'নমস্কার, বীরেন বাবু!',
      'date': 'সোমবার, ৩১ আগস্ট ২০২৬',
      'listenGreeting': 'প্রভাতী বার্তা শুনুন',
      'calmTitle': 'মন শান্ত করুন ও স্মৃতি রোমন্থন',
      'calmDesc': 'পরিচিত ছবি ও গভীর নিঃশ্বাসের মাধ্যমে মানসিক স্বস্তি পান।',
      'sosTitle': 'জরুরী সহায়তা ও সতর্কবার্তা',
      'sosDesc': 'মেয়ে প্রিয়ার কাছে এক-স্পর্শে সংকেত পাঠান।',
      'exercises': 'দৈনিক মানসিক ব্যায়াম',
      'ddaActive': 'অ্যাডাপ্টিভ এআই ইঞ্জিন সক্রিয় (স্তর ২)',
      'game1Title': 'পরিবার চেনার খেলা ("মুখবয়ব")',
      'game1Sub': 'মেয়ে প্রিয়া ও পরিবারের সদস্যদের চিনে নিন।',
      'game2Title': 'দৈনিক কাজের ক্রমবিন্যাস ("দৈনিক ক্রম")',
      'game2Sub': 'চা খাওয়া, ওষুধ খাওয়া ও হাঁটার সঠিক ক্রম সাজান।',
      'game3Title': 'ঐতিহ্যবাহী স্মৃতি মেল ("সংস্কৃতি মেল")',
      'game3Sub': 'জাপী, গামোচা, কাঁসার ঘণ্টা ও বাঁশির জোড় মেলান।',
      'game4Title': 'সুর ও প্রতিধ্বনি স্মৃতি ("ধ্বনি স্মৃতি")',
      'game4Sub': 'মন্দিরের ঘণ্টা ও কোকিলের ডাক চিনুন।',
      'playGame': 'খেলা শুরু করুন',
      'confirmTaken': 'ওষুধ খেয়েছি',
      'listenInstructions': 'নিয়ম শুনুন',
      'schedule': 'বীরেন বাবুর দৈনিক রুটিন',
      'completed': 'সম্পন্ন',
      'pending': 'বাকি আছে',
      'breatheIn': 'গভীর শ্বাস নিন (৪ সেকেন্ড)',
      'breatheHold': 'ধরে রাখুন (৭ সেকেন্ড)',
      'breatheOut': 'ধীরে ধীরে ছাড়ুন (৮ সেকেন্ড)',
      'listenPriyaVoice': 'প্রিয়ার স্বস্তিদায়ক বার্তা শুনুন',
    },
    'hi': {
      'appTitle': 'स्मृति सहायक',
      'brandSubtitle': 'एआई संज्ञानात्मक एवं स्मृति सहायक',
      'greeting': 'नमस्ते, बीरेन बाबू!',
      'date': 'सोमवार, 31 अगस्त 2026',
      'listenGreeting': 'दैनिक संदेश सुनें',
      'calmTitle': 'मन शांत करें व पुरानी यादें',
      'calmDesc': 'पारिवारिक यादों और गहरी सांस के अभ्यास से सुकून पाएं।',
      'sosTitle': 'आपातकालीन सहायता',
      'sosDesc': 'बेटी प्रिया को 1-टच में आपातकालीन सूचना भेजें।',
      'exercises': 'दैनिक संज्ञानात्मक खेल',
      'ddaActive': 'अनुकूली एआई सक्रिय (स्तर 2)',
      'game1Title': 'पारिवारिक चेहरा पहचान ("मुखावयव")',
      'game1Sub': 'अपनी बेटी प्रिया और परिजनों को आवाज से पहचानें।',
      'game2Title': 'दैनिक दिनचर्या क्रम ("दैनिक क्रम")',
      'game2Sub': 'चाय, दवा और टहलने की दिनचर्या को सही क्रम में लगाएं।',
      'game3Title': 'सांस्कृतिक स्मृति मिलान ("संस्कृति मेल")',
      'game3Sub': 'जापी, गमोसा, घंटी और बांसुरी के जोड़े मिलाएं।',
      'game4Title': 'ध्वनि और प्रतिध्वनि स्मृति ("ध्वनि स्मृति")',
      'game4Sub': 'मंदिर की घंटी और कोयल की आवाज को पहचानें।',
      'playGame': 'खेलें',
      'confirmTaken': 'दवा ले ली है',
      'listenInstructions': 'निर्देश सुनें',
      'schedule': 'बीरेन बाबू की दैनिक दिनचर्या',
      'completed': 'पूर्ण',
      'pending': 'बाकी है',
      'breatheIn': 'गहरी सांस लें (4 सेकंड)',
      'breatheHold': 'रोकें (7 सेकंड)',
      'breatheOut': 'धीरे-धीरे छोड़ें (8 सेकंड)',
      'listenPriyaVoice': 'प्रिया का सांत्वना संदेश सुनें',
    }
  };

  static String get(String key, String lang) {
    return localizedValues[lang]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}
